### ISSUE TITLE
Task list 2.0

### ISSUE THREAD

**Issue by llJochemll** [BelgiumHell/Gemini.Altis#13]
Commander
- [ ] Attack
- [ ] Defend
- [ ] Logistics
- [ ] Smart support (CAS, arty, UAV,...)
- [ ] Officers

Misc
- [x] New image firing range
- [x] Radio towers
- [x] Small field camps
- [x] Save system

Code cleanup
- [x] Replace addactions with ace interaction
- [x] Replace nearObjects with nearEntities
- [x] Replace _this select with params
- [x] Replace Bis_fnc_spawn with remoteExec
